package org.dream.basic.pojo.domain;

import java.util.Date;

public class Dept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_dept.dept_id
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private Long deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_dept.parent_id
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_dept.dept_name
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_dept.order_num
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_dept.leader
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private String leader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_dept.phone
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_dept.email
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_dept.status
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_dept.create_by
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_dept.create_time
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_dept.update_by
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_dept.update_time
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_dept.dept_id
     *
     * @return the value of dream_dept.dept_id
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public Long getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_dept.dept_id
     *
     * @param deptId the value for dream_dept.dept_id
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_dept.parent_id
     *
     * @return the value of dream_dept.parent_id
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_dept.parent_id
     *
     * @param parentId the value for dream_dept.parent_id
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_dept.dept_name
     *
     * @return the value of dream_dept.dept_name
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_dept.dept_name
     *
     * @param deptName the value for dream_dept.dept_name
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_dept.order_num
     *
     * @return the value of dream_dept.order_num
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_dept.order_num
     *
     * @param orderNum the value for dream_dept.order_num
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_dept.leader
     *
     * @return the value of dream_dept.leader
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_dept.leader
     *
     * @param leader the value for dream_dept.leader
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setLeader(String leader) {
        this.leader = leader == null ? null : leader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_dept.phone
     *
     * @return the value of dream_dept.phone
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_dept.phone
     *
     * @param phone the value for dream_dept.phone
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_dept.email
     *
     * @return the value of dream_dept.email
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_dept.email
     *
     * @param email the value for dream_dept.email
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_dept.status
     *
     * @return the value of dream_dept.status
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_dept.status
     *
     * @param status the value for dream_dept.status
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_dept.create_by
     *
     * @return the value of dream_dept.create_by
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_dept.create_by
     *
     * @param createBy the value for dream_dept.create_by
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_dept.create_time
     *
     * @return the value of dream_dept.create_time
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_dept.create_time
     *
     * @param createTime the value for dream_dept.create_time
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_dept.update_by
     *
     * @return the value of dream_dept.update_by
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_dept.update_by
     *
     * @param updateBy the value for dream_dept.update_by
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_dept.update_time
     *
     * @return the value of dream_dept.update_time
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_dept.update_time
     *
     * @param updateTime the value for dream_dept.update_time
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}