package org.dream.basic.pojo.domain;

import java.util.Date;

public class Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_post.post_id
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private Long postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_post.post_code
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private String postCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_post.post_name
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private String postName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_post.sort
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_post.status
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_post.create_by
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_post.create_time
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_post.update_by
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_post.update_time
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_post.post_id
     *
     * @return the value of dream_post.post_id
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public Long getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_post.post_id
     *
     * @param postId the value for dream_post.post_id
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_post.post_code
     *
     * @return the value of dream_post.post_code
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_post.post_code
     *
     * @param postCode the value for dream_post.post_code
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_post.post_name
     *
     * @return the value of dream_post.post_name
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getPostName() {
        return postName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_post.post_name
     *
     * @param postName the value for dream_post.post_name
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setPostName(String postName) {
        this.postName = postName == null ? null : postName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_post.sort
     *
     * @return the value of dream_post.sort
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_post.sort
     *
     * @param sort the value for dream_post.sort
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_post.status
     *
     * @return the value of dream_post.status
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_post.status
     *
     * @param status the value for dream_post.status
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_post.create_by
     *
     * @return the value of dream_post.create_by
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_post.create_by
     *
     * @param createBy the value for dream_post.create_by
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_post.create_time
     *
     * @return the value of dream_post.create_time
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_post.create_time
     *
     * @param createTime the value for dream_post.create_time
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_post.update_by
     *
     * @return the value of dream_post.update_by
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_post.update_by
     *
     * @param updateBy the value for dream_post.update_by
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_post.update_time
     *
     * @return the value of dream_post.update_time
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_post.update_time
     *
     * @param updateTime the value for dream_post.update_time
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}