package org.dream.basic.pojo.domain;

import java.util.Date;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_role.role_id
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_role.role_name
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_role.role_key
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private String roleKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_role.sort
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_role.status
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_role.create_by
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_role.create_time
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_role.update_by
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_role.update_time
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_role.role_id
     *
     * @return the value of dream_role.role_id
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_role.role_id
     *
     * @param roleId the value for dream_role.role_id
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_role.role_name
     *
     * @return the value of dream_role.role_name
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_role.role_name
     *
     * @param roleName the value for dream_role.role_name
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_role.role_key
     *
     * @return the value of dream_role.role_key
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getRoleKey() {
        return roleKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_role.role_key
     *
     * @param roleKey the value for dream_role.role_key
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setRoleKey(String roleKey) {
        this.roleKey = roleKey == null ? null : roleKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_role.sort
     *
     * @return the value of dream_role.sort
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_role.sort
     *
     * @param sort the value for dream_role.sort
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_role.status
     *
     * @return the value of dream_role.status
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_role.status
     *
     * @param status the value for dream_role.status
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_role.create_by
     *
     * @return the value of dream_role.create_by
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_role.create_by
     *
     * @param createBy the value for dream_role.create_by
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_role.create_time
     *
     * @return the value of dream_role.create_time
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_role.create_time
     *
     * @param createTime the value for dream_role.create_time
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_role.update_by
     *
     * @return the value of dream_role.update_by
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_role.update_by
     *
     * @param updateBy the value for dream_role.update_by
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_role.update_time
     *
     * @return the value of dream_role.update_time
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_role.update_time
     *
     * @param updateTime the value for dream_role.update_time
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}