package org.dream.basic.pojo.domain;

public class RoleMenuKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_role_menu.role_id
     *
     * @mbg.generated Tue May 26 22:12:13 CST 2020
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_role_menu.menu_id
     *
     * @mbg.generated Tue May 26 22:12:13 CST 2020
     */
    private Long menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_role_menu.role_id
     *
     * @return the value of dream_role_menu.role_id
     *
     * @mbg.generated Tue May 26 22:12:13 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_role_menu.role_id
     *
     * @param roleId the value for dream_role_menu.role_id
     *
     * @mbg.generated Tue May 26 22:12:13 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_role_menu.menu_id
     *
     * @return the value of dream_role_menu.menu_id
     *
     * @mbg.generated Tue May 26 22:12:13 CST 2020
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_role_menu.menu_id
     *
     * @param menuId the value for dream_role_menu.menu_id
     *
     * @mbg.generated Tue May 26 22:12:13 CST 2020
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }
}