package org.dream.basic.pojo.domain;

public class UserPostKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user_post.user_id
     *
     * @mbg.generated Tue May 26 22:12:13 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user_post.post_id
     *
     * @mbg.generated Tue May 26 22:12:13 CST 2020
     */
    private Long postId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user_post.user_id
     *
     * @return the value of dream_user_post.user_id
     *
     * @mbg.generated Tue May 26 22:12:13 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user_post.user_id
     *
     * @param userId the value for dream_user_post.user_id
     *
     * @mbg.generated Tue May 26 22:12:13 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user_post.post_id
     *
     * @return the value of dream_user_post.post_id
     *
     * @mbg.generated Tue May 26 22:12:13 CST 2020
     */
    public Long getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user_post.post_id
     *
     * @param postId the value for dream_user_post.post_id
     *
     * @mbg.generated Tue May 26 22:12:13 CST 2020
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }
}