package org.dream.basic.pojo.domain;

import java.util.Date;

public class User {

    private Long userId;

    private Long deptId;

    private String userName;

    private String nickName;

    private String email;

    private String phone;

    private String sex;

    private String password;

    private String status;

    private String createBy;

    private Date createTime;

    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.update_time
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.user_id
     *
     * @return the value of dream_user.user_id
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.user_id
     *
     * @param userId the value for dream_user.user_id
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.dept_id
     *
     * @return the value of dream_user.dept_id
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public Long getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.dept_id
     *
     * @param deptId the value for dream_user.dept_id
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.user_name
     *
     * @return the value of dream_user.user_name
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.user_name
     *
     * @param userName the value for dream_user.user_name
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.nick_name
     *
     * @return the value of dream_user.nick_name
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.nick_name
     *
     * @param nickName the value for dream_user.nick_name
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.email
     *
     * @return the value of dream_user.email
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.email
     *
     * @param email the value for dream_user.email
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.phone
     *
     * @return the value of dream_user.phone
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.phone
     *
     * @param phone the value for dream_user.phone
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.sex
     *
     * @return the value of dream_user.sex
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.sex
     *
     * @param sex the value for dream_user.sex
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.password
     *
     * @return the value of dream_user.password
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.password
     *
     * @param password the value for dream_user.password
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.status
     *
     * @return the value of dream_user.status
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.status
     *
     * @param status the value for dream_user.status
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.create_by
     *
     * @return the value of dream_user.create_by
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.create_by
     *
     * @param createBy the value for dream_user.create_by
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.create_time
     *
     * @return the value of dream_user.create_time
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.create_time
     *
     * @param createTime the value for dream_user.create_time
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.update_by
     *
     * @return the value of dream_user.update_by
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.update_by
     *
     * @param updateBy the value for dream_user.update_by
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.update_time
     *
     * @return the value of dream_user.update_time
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.update_time
     *
     * @param updateTime the value for dream_user.update_time
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}