package org.dream.basic.pojo.domain;

public class UserRoleKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user_role.user_id
     *
     * @mbg.generated Tue May 26 22:10:17 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user_role.role_id
     *
     * @mbg.generated Tue May 26 22:10:17 CST 2020
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user_role.user_id
     *
     * @return the value of dream_user_role.user_id
     *
     * @mbg.generated Tue May 26 22:10:17 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user_role.user_id
     *
     * @param userId the value for dream_user_role.user_id
     *
     * @mbg.generated Tue May 26 22:10:17 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user_role.role_id
     *
     * @return the value of dream_user_role.role_id
     *
     * @mbg.generated Tue May 26 22:10:17 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user_role.role_id
     *
     * @param roleId the value for dream_user_role.role_id
     *
     * @mbg.generated Tue May 26 22:10:17 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}