server:
  port: 9002

spring:
  application:
    name: dream-microservice-provider
  cloud:
    nacos:
      discovery:
        server-addr: 116.198.160.39:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'