package org.dream.basic.mapper;

import org.dream.basic.pojo.domain.Dept;

public interface DeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_dept
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    int deleteByPrimaryKey(Long deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_dept
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_dept
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    int insertSelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_dept
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    Dept selectByPrimaryKey(Long deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_dept
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    int updateByPrimaryKeySelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_dept
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    int updateByPrimaryKey(Dept record);
}