package org.dream.basic.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.dream.basic.pojo.domain.Menu;

import java.util.List;
@Mapper
public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_menu
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    int deleteByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_menu
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_menu
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_menu
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    Menu selectByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_menu
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_menu
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    int updateByPrimaryKey(Menu record);

    List<Menu> selectRoutesAll();
}