package org.dream.basic.mapper;

import org.dream.basic.pojo.domain.RoleMenuKey;

public interface RoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_role_menu
     *
     * @mbg.generated Tue May 26 22:12:13 CST 2020
     */
    int deleteByPrimaryKey(RoleMenuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_role_menu
     *
     * @mbg.generated Tue May 26 22:12:13 CST 2020
     */
    int insert(RoleMenuKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_role_menu
     *
     * @mbg.generated Tue May 26 22:12:13 CST 2020
     */
    int insertSelective(RoleMenuKey record);
}