package org.dream.basic.mapper;

import org.dream.basic.pojo.domain.RoleDeptKey;

public interface RoleDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_role_dept
     *
     * @mbg.generated Tue May 26 22:12:13 CST 2020
     */
    int deleteByPrimaryKey(RoleDeptKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_role_dept
     *
     * @mbg.generated Tue May 26 22:12:13 CST 2020
     */
    int insert(RoleDeptKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_role_dept
     *
     * @mbg.generated Tue May 26 22:12:13 CST 2020
     */
    int insertSelective(RoleDeptKey record);
}