package org.dream.basic.mapper;

import org.dream.basic.pojo.domain.Role;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_role
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    int deleteByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_role
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_role
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_role
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    Role selectByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_role
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_role
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    int updateByPrimaryKey(Role record);
}