package org.dream.basic.mapper;

import org.dream.basic.pojo.domain.RoleMenu;

public interface RoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_role_menu
     *
     * @mbg.generated Tue May 26 22:12:13 CST 2020
     */
    int deleteByPrimaryKey(RoleMenu key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_role_menu
     *
     * @mbg.generated Tue May 26 22:12:13 CST 2020
     */
    int insert(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_role_menu
     *
     * @mbg.generated Tue May 26 22:12:13 CST 2020
     */
    int insertSelective(RoleMenu record);
}