package org.dream.basic.mapper;

import org.dream.basic.pojo.domain.UserRoleKey;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_user_role
     *
     * @mbg.generated Tue May 26 22:10:17 CST 2020
     */
    int deleteByPrimaryKey(UserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_user_role
     *
     * @mbg.generated Tue May 26 22:10:17 CST 2020
     */
    int insert(UserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_user_role
     *
     * @mbg.generated Tue May 26 22:10:17 CST 2020
     */
    int insertSelective(UserRoleKey record);
}