package org.dream.basic.mapper;

import org.dream.basic.pojo.domain.UserPostKey;

public interface UserPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_user_post
     *
     * @mbg.generated Tue May 26 22:12:13 CST 2020
     */
    int deleteByPrimaryKey(UserPostKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_user_post
     *
     * @mbg.generated Tue May 26 22:12:13 CST 2020
     */
    int insert(UserPostKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_user_post
     *
     * @mbg.generated Tue May 26 22:12:13 CST 2020
     */
    int insertSelective(UserPostKey record);
}