package org.dream.basic.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;
import org.dream.basic.pojo.domain.User;
import org.dream.basic.pojo.vo.UserVO;

import java.util.List;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_user
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_user
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_user
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_user
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    User selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_user
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_user
     *
     * @mbg.generated Sun May 17 15:11:57 CST 2020
     */
    int updateByPrimaryKey(User record);


    @Select("select u.dept_id , u.user_id , u.user_name , u.nick_name , u.email , u.phone , u.sex , u.status , u.create_by , u.create_time , d.dept_name from dream_dept d , dream_user u where d.dept_id = u.dept_id")
    List<UserVO> getUserList();

    List<UserVO> getUserListOfOne(int nodeId);

    List<UserVO> getUserListOfMore(int nodeId);
}